### ISSUE TITLE
Logs spammed with "Invalid entity data item type"

### ISSUE THREAD

**Issue by gloomsys** [qixils/antisocial#1] opened 2023-09-14 21:25 UTC
mod throws this exception whenever a player is loaded regardless if player rendering is enabled or not
```
[14:23:17] [Render thread/ERROR]: Error executing task on Client
java.lang.IllegalStateException: Invalid entity data item type for field 21 on entity class_745['Steve'/362448, l='ClientLevel', x=69, y=69.00, z=69]: old=false(class java.lang.Boolean), new={}(class net.minecraft.class_2487)
	at net.minecraft.class_2945.method_12785(class_2945.java:204) ~[client-intermediary.jar:?]
	at net.minecraft.class_2945.method_12779(class_2945.java:191) ~[client-intermediary.jar:?]
	at net.minecraft.class_634.method_11093(class_634.java:529) ~[client-intermediary.jar:?]
	at net.minecraft.class_2739.method_11808(class_2739.java:46) ~[client-intermediary.jar:?]
	at net.minecraft.class_2739.method_11054(class_2739.java:10) ~[client-intermediary.jar:?]
	at net.minecraft.class_2600.method_11072(class_2600.java:22) ~[client-intermediary.jar:?]
	at net.minecraft.class_1255.method_18859(class_1255.java:156) ~[client-intermediary.jar:?]
	at net.minecraft.class_4093.method_18859(class_4093.java:23) ~[client-intermediary.jar:?]
	at net.minecraft.class_1255.method_16075(class_1255.java:130) ~[client-intermediary.jar:?]
	at net.minecraft.class_1255.method_5383(class_1255.java:115) ~[client-intermediary.jar:?]
	at net.minecraft.class_310.method_1523(class_310.java:1175) ~[client-intermediary.jar:?]
	at net.minecraft.class_310.method_1514(class_310.java:802) ~[client-intermediary.jar:?]
	at net.minecraft.client.main.Main.main(Main.java:250) ~[minecraft-1.20.1-client.jar:?]
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:468) ~[fabric-loader-0.14.21.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74) ~[fabric-loader-0.14.21.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23) ~[fabric-loader-0.14.21.jar:?]
	at org.prismlauncher.launcher.impl.StandardLauncher.launch(StandardLauncher.java:88) ~[NewLaunch.jar:?]
	at org.prismlauncher.EntryPoint.listen(EntryPoint.java:126) ~[NewLaunch.jar:?]
	at org.prismlauncher.EntryPoint.main(EntryPoint.java:71) ~[NewLaunch.jar:?]
```

**Comment by qixils** [comment] 2023-09-14 21:58
Heya @kirikarma, can't say I've seen this before. I don't see antisocial in the stacktrace at all. What all mods do you have installed? What server are you playing on, or is this LAN?

**Comment by qixils** [comment] 2023-09-14 22:13
Are you certain this issue only occurs when Antisocial is installed? All functions are a no-op when rendering isn't being skipped and I don't mess with packets in anyway (which is where is crash is occurring) so I really doubt Antisocial is the cause...

**Comment by qixils** [comment] 2023-09-16 00:54
Yeah, I don't add any extra "entity data items." Feel free to comment with further info but I don't believe my mod is responsible for this so I'm closing this for now.

**Closed as not planned by qixils** 2023-09-16 00:54 UTC
Labels: bug, needs more info

**Comment by gloomsys** [comment] 2023-09-23 17:32
Forgot to respond sorry :skull:

**Comment by qixils** [comment] 2023-09-23 17:34
No worries 🙂
